namespace DuskOfCoding.Domain.Models;

public record Feedback
{
    public bool IsSuccess { get; init; }
    public string Summary { get; init; } = string.Empty;
    public IReadOnlyList<string> CompilationMessages { get; init; } = Array.Empty<string>();
    public IReadOnlyList<string> TestMessages { get; init; } = Array.Empty<string>();
    
    /// <summary>
    /// Optional structured feedback generated by an AI review step.
    /// </summary>
    public string? AiReviewRemarks { get; init; }
}
